/**:
  ros__parameters:
    dst_ip: 10.2.10.31                 # the IP address of the pan and tilt module (for communicaton over a MOXA)
    port: 4016                        # the port to send messages to (if using a MOXA)
    from_addr: 1                      # the value to fill the "from" address field in the packet header
    to_addr: 3                        # the value to fill the "to" address field in the packet header
    joy_topic: /odysseus4k/control/joy/pan_tilt        # the joystick topic you want to control the P/T with
    max_joy_age: 1.0                  # how old can a joystick messsage be before we center it
    pan_axis: 0                       # the joystick axis you want for panning
    pan_gain: -1.0                     # a multiplier for the pan axis  negative value to invert axis
    tilt_axis: 1                      # the joystick axis you want for tilting
    tilt_gain: 1.0                    # a multiplier for the tilt axis  negative value to invert axiss
    joy_deadband: 0.2                # axis deadband (0.0–1.0); values within ±this of center are treated as 0
    minimum_speed: 50               # minimum speed command (0–100) when commanding any motion; non-zero commands below this are snapped up
